theme = "onedark"

[editor]
line-number = "relative"
cursorline = true
bufferline = "multiple"
auto-pairs = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "file-base-name", "read-only-indicator", "file-modification-indicator"]
center = ["spinner"]
right = ["diagnostics", "selections", "position", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
enable = true

[editor.whitespace.render]
tab = "all"
